### ISSUE TITLE
aurora namespace question

### ISSUE THREAD

**Issue by kkappler** [andykee/aurora#1]
Hi Andy, 

We haven't met.  I am working on opensource software for processing of magnetotelluric (MT) data with the SimPEG group from University of British Columbia geophysics department and the USGS.  We planned to release on conda-forge and pypi this coming month as "aurora" (because MT uses natural fluctuations in the earth's magnetic field as the illuminating field) and noticed that you are using the namespace.  Just wondering how tied you are to the package name and if you would consider letting us use if for the project.  Totally understand if not -- but it couldn't hurt to ask right?

thanks for your consideration, 

Karl Kappler and (hopefully) the Aurora team.

**Comment by andykee** [comment]
Hi Karl,

I think my aurora library is probably headed for the recycling bin anyways, so I’m happy to release the PyPi namespace. Reach out when you’re ready with something to publish and I’ll happily remove my project. 

We should coordinate some convenient time for me to delete my project. I don’t think there’s much lag between when I release the name and when it becomes available for anyone to grab. I’d hate for me to release it today only to have someone snag it before you’re ready to use it yourself. You can always just publish version 0.0.1 with nothing but a README, which is essentially what I did. 

Andy

**Comment by kkappler** [comment]
Thank you so much Andy,

We really appreciate it!    Probably the easiest way to do a smooth
changeover would be live.  Lindsey Heagy at UBC is the lead for the
open-source software management and we have a weekly tag up Wednesdays at
2pm.

Would one of June 9 or 16 work for you at 2pm Pacific Time?  You could join
Lindsey and I for a few minutes and we can do the changeout.

Here is a link to the meeting room we are using, we use the same link every
week;

Wednesdays, · 14:00 – 15:00
Google Meet joining info
Video call link: https://meet.google.com/tuv-vuzr-xks

cheers,

Karl

**Comment by andykee** [comment]
Let’s do the 16th. I’ll join the meeting at 2pm Pacific.

**Comment by kkappler** [comment]
Great! See you then.

**Comment by kkappler** [comment]
Hi Andy,

Just a reminder email that we had planned to tag up at 2pm this afternoon.
Looking forward to meeting you there.

Karl

Video call link: https://meet.google.com/tuv-vuzr-xks

**Comment by andykee** [comment]
I'll be there!

AK
